version: '3.8'

services:
  app:
    image: python:3.10-slim
    command: tail -f /dev/null
    volumes:
      - .:/app
    working_dir: /app

  target-linux:
    build: 
      context: ./target
    privileged: true
    ports:
      - "8080:8080"
